### ISSUE TITLE
Debug messages are logged as configuration errors

### ISSUE THREAD

**Issue by davidjb** [kvspb/nginx-auth-ldap#103]
The changes in https://github.com/kvspb/nginx-auth-ldap/commit/e5ec5742499cc301325cba13f0e0f15a3706f490 are echoed to the console whenever ``require`` is being parsed (eg on every server restart).  The commit logs these debug messages as configuration errors (eg ``ngx_conf_log_error``) when they're valid configuration.

If they're debugging messages, they should be using ``ngx_log_debugX`` instead (where X is the number of arguments).

**Comment by brunoqc** [comment]
This is a duplicate of #88

**Comment by davidjb** [comment]
Self-closing due to this being a dupe.
