### ISSUE TITLE
nginx-auth-ldap/ngx_http_auth_ldap_module.c:395:8: 警告：#warning "http_auth_ldap: Compiling with OpenSSL < 1.0.2

### ISSUE THREAD

**Issue by zhanghao1013** [kvspb/nginx-auth-ldap#142]
my openssl version:
[root@wusong nginx-1.11.0]# openssl version
OpenSSL 1.0.2h  3 May 2016

What is the situation？

**Comment by guileinsighter** [comment]
Hi zhanghao1013,

Did you find any solutions? If so, what was it?

**Comment by zhanghao1013** [comment]
./configure --prefix=/etc/nginx --add-module=ldap_module_path
