### ISSUE TITLE
This documentation sucks

### ISSUE THREAD

**Issue by janboll** [kvspb/nginx-auth-ldap#149]
The documentation of the configuration parameters is just garbage. Seriously, if you want anybody to use your software please provide a proper documentation of the parameters and their meaning.

I do not ask for something like examples, but just a proper explanation of the parameters and their effects. 

_Example_: require - expected value: valid_user, user, group 
So what happens if i set valid_user? What is a valid user? What happens if i set group?

**Comment by Leryan** [comment]
You're rude, dude. And how do you know "they" want this software to be used by anybody?

This is free & open source software.

A better issue would be to start explaining configuration parameters.

**Comment by janboll** [comment]
I am sorry for my bad manners.
👎
