### ISSUE TITLE
ngx_http_auth_ldap_module.c:33:18: fatal error: ldap.h: No such file or directory

### ISSUE THREAD

**Issue by alexeikaratai** [kvspb/nginx-auth-ldap#172]
ngx_http_auth_ldap_module.c:33:18: fatal error: ldap.h: No such file or directory

**Comment by marcowork** [comment]
+1

**Comment by gdelpierre** [comment]
Hi, 

If you are running debian like OS try ```apt-get install libldap2-dev```
