### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by wjimenez5271** [kvspb/nginx-auth-ldap#5]
I tried compiling this with nginx 1.2.6 and encountered the following errors:

/opt/nginx/nginx-auth-ldap//ngx_http_auth_ldap_module.c:12:18: error: ldap.h: No such file or directory
/opt/nginx/nginx-auth-ldap//ngx_http_auth_ldap_module.c:30: error: expected specifier-qualifier-list before ‘LDAPURLDesc’
/opt/nginx/nginx-auth-ldap//ngx_http_auth_ldap_module.c:66: error: ‘ngx_http_auth_ldap_loc_conf_t’ has no member named ‘realm’
/opt/nginx/nginx-auth-ldap//ngx_http_auth_ldap_module.c:80: error: ‘ngx_http_auth_ldap_loc_conf_t’ has no member named ‘bind_dn’
/opt/nginx/nginx-auth-ldap//ngx_http_auth_ldap_module.c:87: error: ‘ngx_http_auth_ldap_loc_conf_t’ has no member named ‘bind_dn_passwd’
/opt/nginx/nginx-auth-ldap//ngx_http_auth_ldap_module.c:108: error: ‘ngx_http_auth_ldap_loc_conf_t’ has no member named ‘group_attribute’
/opt/nginx/nginx-auth-ldap//ngx_http_auth_ldap_module.c:115: error: ‘ngx_http_auth_ldap_loc_conf_t’ has no member named ‘group_attribute_dn’
cc1: warnings being treated as errors

Is there a missing library I need? I see a reference to an ldap.h file.

**Comment by nirbhabbarat** [comment]
On CentOS 6.5, my issue sorted by installing openldap-devel

**Comment by snowshine09** [comment]
After installing openldap-devel, my error still exists - I am running on Linux 3.10.0-514.6.1.el7.x86_64. This is a big hurdle for me to install the ldap-client package using node npm. Could someone help with me on this?
``make: Entering directory `/home/Workspace/slack-weare/node_modules/ldap-client/build'
  CXX(target) Release/obj.target/LDAPCnx/LDAP.o
In file included from ../LDAP.cc:2:0:
../LDAPCnx.h:5:18: fatal error: ldap.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/LDAPCnx/LDAP.o] Error 1
