### ISSUE TITLE
What do I introduce in binddn  and binddn_passwd ? nginx: [emerg] http_auth_ldap: parse_require

### ISSUE THREAD

**Issue by juandasgandaras** [kvspb/nginx-auth-ldap#96]
Hi 

I want to connect nginx to ldap server to have Auth a group-membership so I guess this configuration 

ldap_server test1 {
  url ldap://192.168.0.1:3268/DC=test,DC=local?sAMAccountName?sub?(objectClass=person);
  binddn "TEST\\LDAPUSER";
  binddn_passwd LDAPPASSWORD;
  group_attribute member;
  group_attribute_is_dn on;
  require group 'CN=group,DC=test,DC=local';
  require valid_user;
}

But I do not that introduce in the parameters:

binddn "TEST\\LDAPUSER";
binddn_passwd LDAPPASSWORD;

And I am havin the next error:

nginx: [emerg] http_auth_ldap: parse_require in /home/jdiazg/nginx/nginx_ldap/nginx-binnaries//conf/nginx.conf:65
nginx: [emerg] http_auth_ldap: Setting group in /home/jdiazg/nginx/nginx_ldap/nginx-binnaries//conf/nginx.conf:65
nginx: [emerg] http_auth_ldap: parse_require in /home/jdiazg/nginx/nginx_ldap/nginx-binnaries//conf/nginx.conf:66

2015/08/10 16:27:58 [error] 27125#0: http_auth_ldap: Could not connect
2015/08/10 16:27:59 [error] 26452#0: http_auth_ldap: Could not connect

Could somebody give me an advice?

Thanks.

**Comment by Illydth** [comment]
I've found that the binddn user must exist in the URL Location listed in the "url" configuration and your binddn should probably be the full DN path within the AD/LDAP server to your bind user (i.e. CN=<username>,OU=<folder>,OU=<folder>,...,DC=<domain>,DC=<ext>)

E.g. CN=MyUser,OU=Admins,OU=Corporate,OU=Users,DC=test,DC=com

This would specify "MyUser" in the LDAP Structure "test.com->Users->Corporate->Admins"

That said, parse_require generally denotes an issue parsing the line.  Make sure you're using ";" at the end of each line of NGINX config.

**Comment by juandasgandaras** [comment]
ok thanks for your help
